### ISSUE TITLE
Создать свою карту сервера

### ISSUE THREAD

**Issue by fedKotikeD** [fedKotikeD-org/Bluespace-Station#21]
### Описание

Создать новую карту на подобии Box для нашего сервера. Маппер будет награждён. Итоговый вариант запихнуть в Resources/Maps/Bluespace.yml в server content

### Параметры

1. Она должна быть большая
2. Обязательно: инженерия, атмос, Бриг, пермабриг, мостик, мед (с химией), кабинеты глав, РНД, техи, карго, мостик, ИИ, эвак, театр, бар
3. Всякие баги которые я отмечу - пофиксить!

**Comment by dopoi16-txt** [comment]
Сделаю
